kind: pipeline
name: default

workspace:
  base: /book
  path: the-way-to-go_ZH_CN

steps:
- name: prepare
  image: alpine:3.10
  commands:
  - sh ./prepare.sh
- name: build
  image: panbook:latest
  pull: if-not-exists
  commands:
  - panbook book -d
  depends_on:
  - prepare
 
- name: publish
  image: annprog/rsync:latest
  pull: if-not-exists
  settings:
    src: build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - build