kind: pipeline
name: default

workspace:
  base: /book
  path: the-way-to-go_ZH_CN

steps:
- name: prepare
  image: alpine:3.10
  commands:
  - mv eBook src
  - mv images/* src/images
  - sed -i 's#../images/#images/#g' src/*.md
  - rm -f src/frontmatter.md
  - mv src/preface.md src/frontmatter.md
  - sed -i '/- \[目录\].*/d' src/*.md
  - sed -i '/^- \[上一*\].*/d' src/*.md
  - sed -i '/^- \[下一*\].*/d' src/*.md
- name: build
  image: panbook:latest
  pull: if-not-exists
  commands:
  - panbook book -d
  depends_on:
  - prepare
 
- name: publish
  image: annprog/rsync:latest
  pull: if-not-exists
  settings:
    src: build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - build