kind: pipeline
name: default

workspace:
  base: /book
  path: the-way-to-go_ZH_CN

steps:
- name: ctexbook
  image: panbook:latest
  pull: if-not-exists
  commands:
  - MEM=--memory=650m make ctexbook
  
- name: elegantbook
  image: panbook:latest
  pull: if-not-exists
  commands:
  - MEM=--memory=650m make elegantbook
  depends_on:
  - ctexbook

- name: publish
  image: annprog/rsync:latest
  pull: if-not-exists
  settings:
    src: build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - ctexbook
  - elegantbook